//package com.company;

public class RakeLanguages {
    static String ARABIC = "ar";
    static String ARMENIAN = "hy";
    static String BASQUE = "eu";
    static String BENGALI = "bn";
    static String BULGARIAN = "bg";
    static String CATALAN = "ca";
    static String CHINESE_PRC = "zh_cn";
    static String CHINESE_TAIWAN = "zh_tw";
    static String CROATIAN = "hr";
    static String CZECH = "cs";
    static String DANISH = "da";
    static String DUTCH = "nl";
    static String ENGLISH = "en";
    static String FINNISH = "fi";
    static String FRENCH = "fr";
    static String GALICIAN = "gl";
    static String GERMAN = "de";
    static String GREEK = "el";
    static String HEBREW = "he";
    static String HINDU = "hi";
    static String HUNGARIAN = "hu";
    static String INDONESIAN = "id";
    static String IRISH = "ga";
    static String ITALIAN = "it";
    static String JAPANESE = "ja";
    static String KOREAN = "ko";
    static String KURDISH = "ku";
    static String LATVIAN = "lv";
    static String LITHUANIAN = "lt";
    static String MARATHI = "mr";
    static String NORSK = "no";
    static String PERSIAN = "fa";
    static String POLISH = "pl";
    static String PORTUGUESE = "pt";
    static String PORTUGUESE_BRAZIL = "pt_br";
    static String ROMANIAN = "ro";
    static String RUSSIAN = "ru";
    static String SLOVAK = "sk";
    static String SPANISH = "es";
    static String SWEDISH = "sv";
    static String THAI = "th";
    static String TURKISH = "tr";
    static String UKRAINIAN = "uk";
    static String URDU = "ur";
}
